<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-FVF3EU5" failures="2" tests="7" name="Test" time="80.506" errors="0" timestamp="2025-07-28T20:45:42 IST">
  <testcase classname="testCases.TC001_AccountRegistration" name="verify_account_registration" time="2.632"/>
  <testcase classname="testCases.TC002_Login" name="logintest" time="2.195"/>
  <testcase classname="testCases.TC003_Login_DD" name="logintest" time="12.746"/>
  <testcase classname="testCases.TC003_Login_DD" name="logintest" time="15.616">
    <failure type="java.lang.AssertionError" message="Login succeeded, but was expected to fail.">
      <![CDATA[java.lang.AssertionError: Login succeeded, but was expected to fail.
at testCases.TC003_Login_DD.logintest(TC003_Login_DD.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
  <testcase classname="testCases.TC003_Login_DD" name="logintest" time="11.747"/>
  <testcase classname="testCases.TC003_Login_DD" name="logintest" time="11.964">
    <failure type="java.lang.AssertionError" message="Login failed, but was expected to succeed.">
      <![CDATA[java.lang.AssertionError: Login failed, but was expected to succeed.
at testCases.TC003_Login_DD.logintest(TC003_Login_DD.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
  <testcase classname="testCases.TC003_Login_DD" name="logintest" time="12.269"/>
</testsuite> <!-- Test -->
